Repository 2024-OS/node, pull requests merged in 2024-11, with the labels that each got.

#5 chore: OS 아이콘 추가
  app/src/main/res/drawable/img.png
  app/src/main/res/layout/fragment_plan_list.xml
Labels: 개선

#6 feat & chore: 배경색 변환
  app/src/main/res/layout/fragment_plan_list.xml
Labels: 개선

#7 feat & chore: 배경색 변경 및 버튼 위치 변경
  app/src/main/res/layout/fragment_plan_list.xml
Labels: 개선, 작업 중

#8 Update fragment_plan_list.xml
  app/src/main/res/layout/fragment_plan_list.xml
Labels: 버그

#10 feat, chore: 예산안 레이아웃 설정
  app/src/main/java/com/example/node_project/Budget.kt
  app/src/main/java/com/example/node_project/BudgetFragment.kt
  app/src/main/java/com/example/node_project/MyItemRecyclerViewAdapter.kt
  app/src/main/java/com/example/node_project/MyItemRecyclerViewAdapter2.kt
  app/src/main/res/drawable/del.png
  app/src/main/res/drawable/picture.png
  app/src/main/res/drawable/receipt.png
  app/src/main/res/drawable/resource__.png
  app/src/main/res/drawable/white_circle.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/fragment_calender.xml
  app/src/main/res/layout/fragment_cash.xml
  app/src/main/res/layout/fragment_cash2.xml
  app/src/main/res/layout/fragment_item_list.xml
  app/src/main/res/layout/fragment_plan_list.xml
  app/src/main/res/layout/fragment_plan_list2.xml
  app/src/main/res/navigation/nav_main.xml
Labels: 토론 필요

#12 fix: 하단 바가 안 보이는 오류 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_calender.xml
  app/src/main/res/layout/fragment_cash.xml
  app/src/main/res/layout/fragment_cash2.xml
  app/src/main/res/layout/fragment_plan_list.xml
  app/src/main/res/layout/fragment_plan_list2.xml
Labels: 버그, 개선, 완료

#13 feat: 하단바 기능 추가
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/node_project/BudgetFragment.kt
  app/src/main/java/com/example/node_project/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/nav_main.xml
Labels: 개선

#14 feat: 화면버그 수정
  app/src/main/res/layout/activity_main.xml
Labels: 개선

#15 docs, refactor, chore: 디자인 일관성 및 필요 없는 주석삭제
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/node_project/Budget2.kt
  app/src/main/java/com/example/node_project/BudgetFragment.kt
  app/src/main/java/com/example/node_project/Calender_Fragment.kt
  app/src/main/java/com/example/node_project/Cash.kt
  app/src/main/java/com/example/node_project/Cash2.kt
  app/src/main/java/com/example/node_project/ItemFragment.kt
  app/src/main/java/com/example/node_project/MyItemRecyclerViewAdapter.kt
  app/src/main/java/com/example/node_project/MyItemRecyclerViewAdapter2.kt
  app/src/main/java/com/example/node_project/PlanList.kt
  app/src/main/java/com/example/node_project/PlanList2.kt
  app/src/main/java/com/example/node_project/Plan_List.kt
  app/src/main/java/com/example/node_project/fragment_calender.kt
  app/src/main/res/drawable/del.png
  app/src/main/res/drawable/img.png
  app/src/main/res/drawable/resource__.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/fragment_calender.xml
  app/src/main/res/layout/fragment_cash.xml
  app/src/main/res/layout/fragment_cash2.xml
  app/src/main/res/layout/fragment_plan_list.xml
  app/src/main/res/layout/fragment_plan_list2.xml
  app/src/main/res/navigation/nav_main.xml
Labels: 문서작업, 개선, 중요, 토론 필요

#17 feat: budget 코드 수정 및 추가
  app/src/main/java/com/example/node_project/BudgetAdapter.kt
  app/src/main/java/com/example/node_project/BudgetFragment.kt
  app/src/main/java/com/example/node_project/BudgetItem.kt
  app/src/main/java/com/example/node_project/ItemFragment.kt
  app/src/main/java/com/example/node_project/MainActivity.kt
  app/src/main/java/com/example/node_project/MyItemRecyclerViewAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/fragment_item_list.xml
  app/src/main/res/layout/item_budget.xml
  app/src/main/res/navigation/nav_main.xml
Labels: 버그, 도움 요청, 작업 중

#19 feat: 링크 입력칸 추가
  app/src/main/java/com/example/node_project/BudgetAdapter.kt
  app/src/main/java/com/example/node_project/BudgetItem.kt
  app/src/main/res/layout/item_budget.xml
Labels: 개선

#20 feat: 장소선정 리스트 추가
  app/src/main/java/com/example/node_project/PlanItem.kt
  app/src/main/java/com/example/node_project/PlanList.kt
  app/src/main/java/com/example/node_project/PlanListAdapter.kt
  app/src/main/res/drawable/heart.png
  app/src/main/res/layout/fragment_plan_list.xml
  app/src/main/res/layout/item_plan.xml
Labels: 작업 중

#23 feat: 캘린더 기능 추가
  app/src/main/java/com/example/node_project/CalendarFragment.kt
  app/src/main/java/com/example/node_project/ScheduleAdapter.kt
  app/src/main/java/com/example/node_project/ScheduleItem.kt
  app/src/main/java/com/example/node_project/fragment_calender.kt
  app/src/main/res/layout/fragment_calender.xml
  app/src/main/res/layout/item_schedule.xml
Labels: 개선, 작업 중

#25 feat,chore: 회계내역 입력 및 OS 전체 위치 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/node_project/Cash.kt
  app/src/main/java/com/example/node_project/CashItem.kt
  app/src/main/java/com/example/node_project/CashItemFragment.kt
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/fragment_cash.xml
  app/src/main/res/layout/fragment_cash_item.xml
  app/src/main/res/layout/fragment_plan_list.xml
  app/src/main/res/layout/fragment_plan_list2.xml
Labels: 개선, 완료

#26 feat: 캘린더와 예산안 레이아웃 수정
  app/src/main/java/com/example/node_project/CalendarFragment.kt
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/fragment_calender.xml
Labels: 개선

#38 fear: 예산안 리스트에 firebase추가
  app/src/main/java/com/example/node_project/BudgetAdapter.kt
  app/src/main/java/com/example/node_project/BudgetFragment.kt
  app/src/main/java/com/example/node_project/BudgetItem.kt
  app/src/main/java/com/example/node_project/BudgetViewModel.kt
  app/src/main/java/com/example/node_project/MyItemRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/item_budget.xml
Labels: 개선

#39 feat: 링크 접속 기능 추가
  app/src/main/java/com/example/node_project/BudgetAdapter.kt
  app/src/main/res/layout/item_budget.xml
Labels: 개선

#43 feat: 날짜 오류 수정
  app/src/main/java/com/example/node_project/CalendarViewModel.kt
Labels: 개선
